name: Feature Request
description: Suggest a new feature or improvement for NostalgiApp
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make NostalgiApp better? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve? What use case does it address?
      placeholder: This would help because...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - User Interface
        - Game Library
        - Performance
        - Emulation
        - Settings
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or mockups
    validations:
      required: false
